name: Calculator

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requisitos.txt
    - name: Run tests
      run: |
        pytest